# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScreenRecord' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ScreenRecord
  pod 'Masonry'
  pod 'LYPScreenRecord'

  target 'ScreenRecordTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScreenRecordUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
